// Mapping nomi provincia italiani → sigla 2 lettere (codice ISO 3166-2:IT)
// eBay Sell Inventory API richiede la sigla a 2 lettere per stateOrProvince in Italia.

const PROVINCE_IT: Record<string, string> = {
  'agrigento': 'AG',
  'alessandria': 'AL',
  'ancona': 'AN',
  'aosta': 'AO',
  'arezzo': 'AR',
  'ascoli piceno': 'AP',
  'asti': 'AT',
  'avellino': 'AV',
  'bari': 'BA',
  'barletta-andria-trani': 'BT',
  'belluno': 'BL',
  'benevento': 'BN',
  'bergamo': 'BG',
  'biella': 'BI',
  'bologna': 'BO',
  'bolzano': 'BZ',
  'brescia': 'BS',
  'brindisi': 'BR',
  'cagliari': 'CA',
  'caltanissetta': 'CL',
  'campobasso': 'CB',
  'caserta': 'CE',
  'catania': 'CT',
  'catanzaro': 'CZ',
  'chieti': 'CH',
  'como': 'CO',
  'cosenza': 'CS',
  'cremona': 'CR',
  'crotone': 'KR',
  'cuneo': 'CN',
  'enna': 'EN',
  'fermo': 'FM',
  'ferrara': 'FE',
  'firenze': 'FI',
  'foggia': 'FG',
  'forli-cesena': 'FC',
  'forlì-cesena': 'FC',
  'frosinone': 'FR',
  'genova': 'GE',
  'gorizia': 'GO',
  'grosseto': 'GR',
  'imperia': 'IM',
  'isernia': 'IS',
  'la spezia': 'SP',
  "l'aquila": 'AQ',
  'l aquila': 'AQ',
  'latina': 'LT',
  'lecce': 'LE',
  'lecco': 'LC',
  'livorno': 'LI',
  'lodi': 'LO',
  'lucca': 'LU',
  'macerata': 'MC',
  'mantova': 'MN',
  'massa-carrara': 'MS',
  'massa carrara': 'MS',
  'matera': 'MT',
  'messina': 'ME',
  'milano': 'MI',
  'modena': 'MO',
  'monza e della brianza': 'MB',
  'monza-brianza': 'MB',
  'monza brianza': 'MB',
  'napoli': 'NA',
  'novara': 'NO',
  'nuoro': 'NU',
  'oristano': 'OR',
  'padova': 'PD',
  'palermo': 'PA',
  'parma': 'PR',
  'pavia': 'PV',
  'perugia': 'PG',
  'pesaro e urbino': 'PU',
  'pesaro-urbino': 'PU',
  'pescara': 'PE',
  'piacenza': 'PC',
  'pisa': 'PI',
  'pistoia': 'PT',
  'pordenone': 'PN',
  'potenza': 'PZ',
  'prato': 'PO',
  'ragusa': 'RG',
  'ravenna': 'RA',
  'reggio calabria': 'RC',
  'reggio emilia': 'RE',
  'rieti': 'RI',
  'rimini': 'RN',
  'roma': 'RM',
  'rovigo': 'RO',
  'salerno': 'SA',
  'sassari': 'SS',
  'savona': 'SV',
  'siena': 'SI',
  'siracusa': 'SR',
  'sondrio': 'SO',
  'sud sardegna': 'SU',
  'taranto': 'TA',
  'teramo': 'TE',
  'terni': 'TR',
  'torino': 'TO',
  'trapani': 'TP',
  'trento': 'TN',
  'treviso': 'TV',
  'trieste': 'TS',
  'udine': 'UD',
  'varese': 'VA',
  'venezia': 'VE',
  'verbano-cusio-ossola': 'VB',
  'vercelli': 'VC',
  'verona': 'VR',
  'vibo valentia': 'VV',
  'vicenza': 'VI',
  'viterbo': 'VT',
};

export function normalizeProvinciaIt(input: string): string {
  const key = input.trim().toLowerCase();
  // Se è già un codice 2 lettere, lascia così
  if (/^[A-Z]{2}$/i.test(key)) return key.toUpperCase();
  return PROVINCE_IT[key] ?? input.trim();
}
